name: Kesinti Bot

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 18 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Gerekli paketler
      run: pip install requests

    - name: Botu çalıştır
      run: python bot.py
